### ISSUE TITLE
Create snippet showing to use HAProxy as load-balancer

### ISSUE THREAD

**Issue by louiscryan** [grpc/grpc-experiments#144]
Should be realtively straightforward for HAProxy. Largely following the recipe here

https://www.igvita.com/2012/10/31/simple-spdy-and-npn-negotiation-with-haproxy/

but adjusting for HTTP2 and ALPN.

Currently nghttp2 does not support multiple http2 backends but if it did we should have a recipe for that.

**Comment by thpham** [comment]
Hello @louiscryan , I'm trying to setup HAProxy (1.5.14) to validate if it's possible to load balance a gRPC client with multiple servers (with the four kinds of service and all the benefits of gRPC). I started from your (google) example in grpc-java (route-guide-server) and I modified it a bit to be able to start the server on different ports with an argument. Then I setup HAProxy both in both http/tcp mode but without success, because the client crash when it try to connect with HAProxy. I read on HAProxy website news that they expect the support of http/2 by the end of the year with v1.7.  We (my company and I) would love to start a new ambitious project with gRPC, but being able to scale and having failover capabilities is really mandatory !

 Can you confirm it won't work until they add HTTP/2 support or give me an alternative if you think there is ?  (Does GoogleCloud load balancer in beta already support HTTP/2 ?)...

Thank you !

**Comment by louiscryan** [comment]
So you can still use HAProxy to do layer 3 load balancing instead of layer 7. Take a look at the documentation that Jetty uses to do just this.

https://www.eclipse.org/jetty/documentation/current/http2-configuring-haproxy.html

The setup for GRPC is essentially the same, you want to make sure your GRPC server is setup to accept   HTTP2 over plaintext as HAProxy will terminal TLS for you

**Comment by breerly** [comment]
Anyone have any luck here?

**Comment by louiscryan** [comment]
I did before, were you getting stuck on something?

**Comment by proteneer** [comment]
Doesn't layer 3 load balancing operate on the connection level (that is, only relevant when you have a large number of clients with a small number of servers)?

the inverse case where you have one client but a ton of servers isn't satisfied by layer 3 load balancing.

**Comment by louiscryan** [comment]
If Layer3 isn't useful and you need Layer7 then try out

https://nghttp2.org/documentation/nghttpx.1.html
